version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_DATABASE=SkiStationDB
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      - $PWD/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  spring_app:
    depends_on:
      - db
    build: ./
    container_name: ski
    image: ski
    restart: on-failure
    ports:
      - '8085:8085'
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url"  : "jdbc:mysql://db:3306/SkiStationDB?useSSL=false",
           "spring.datasource.username" : "root",
           "spring.datasource.password" : "root",
           "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
           "spring.jpa.hibernate.ddl-auto" : "update"
         }'
volumes:
  mysql:
    driver: local